# Generated by Plazma Game Engine! We hope you've enjoyed using our engine!
# Email: 'unstableplazma@gmail.com'

import pygame as pg

objects = [pg.Rect(0, 0, 100, 100), pg.Rect(100, 0, 100, 100), pg.Rect(200, 0, 100, 100), pg.Rect(300, 0, 100, 100), pg.Rect(400, 0, 100, 100), pg.Rect(500, 0, 100, 100), pg.Rect(600, 0, 100, 100), pg.Rect(700, 0, 100, 100), pg.Rect(800, 0, 100, 100), pg.Rect(900, 0, 100, 100), pg.Rect(1000, 0, 100, 100), pg.Rect(1100, 0, 100, 100), pg.Rect(1100, 100, 100, 100), pg.Rect(1100, 200, 100, 100)]
objectTypes = [0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 2, 2, 2, 2]

def loadMap():
    return objects, objectTypes
# Thank you using our engine! We hope you've enjoyed using it!
# - UnstablePlazma

