# Generated by Plazma Game Engine! We hope you've enjoyed using our engine!
# Email: 'unstableplazma@gmail.com'

import pygame as pg

objects = [pg.Rect(0, 0, 100, 100), pg.Rect(100, 0, 100, 100), pg.Rect(200, 0, 100, 100), pg.Rect(300, 0, 100, 100), pg.Rect(400, 0, 100, 100), pg.Rect(500, 0, 100, 100), pg.Rect(600, 0, 100, 100), pg.Rect(700, 0, 100, 100), pg.Rect(800, 0, 100, 100), pg.Rect(900, 0, 100, 100), pg.Rect(1000, 0, 100, 100), pg.Rect(1100, 0, 100, 100), pg.Rect(1100, 100, 100, 100), pg.Rect(1100, 200, 100, 100), pg.Rect(1100, 300, 100, 100), pg.Rect(1100, 400, 100, 100), pg.Rect(1100, 500, 100, 100), pg.Rect(1100, 600, 100, 100), pg.Rect(1100, 700, 100, 100), pg.Rect(1000, 700, 100, 100), pg.Rect(900, 700, 100, 100), pg.Rect(800, 700, 100, 100), pg.Rect(700, 700, 100, 100), pg.Rect(600, 700, 100, 100), pg.Rect(500, 700, 100, 100), pg.Rect(400, 700, 100, 100), pg.Rect(300, 700, 100, 100), pg.Rect(200, 700, 100, 100), pg.Rect(100, 700, 100, 100), pg.Rect(0, 700, 100, 100), pg.Rect(0, 600, 100, 100), pg.Rect(0, 500, 100, 100), pg.Rect(0, 400, 100, 100), pg.Rect(0, 300, 100, 100), pg.Rect(0, 200, 100, 100), pg.Rect(0, 100, 100, 100), pg.Rect(800, 500, 100, 100), pg.Rect(900, 500, 100, 100), pg.Rect(800, 400, 100, 100), pg.Rect(900, 400, 100, 100), pg.Rect(600, 200, 100, 100), pg.Rect(500, 200, 100, 100)]
objectTypes = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1]

portals = [pg.Rect(100, 350, 100, 100), pg.Rect(1000, 350, 100, 100)]
portalLocations = ['perimeter', 'maze']

def loadMap():
    return objects, objectTypes, portals, portalLocations
# Thank you using our engine! We hope you've enjoyed using it!
# - UnstablePlazma

