# Generated by Plazma Game Engine! We hope you've enjoyed using our engine!
# Email: 'unstableplazma@gmail.com'

import pygame as pg

objects = []
objectTypes = []

portals = [pg.Rect(0, 350, 100, 100)]
portalLocations = ['e']

def loadMap():
    return objects, objectTypes, portals, portalLocations
# Thank you using our engine! We hope you've enjoyed using it!
# - UnstablePlazma

